"""
This script updates Omeka S database items with French summaries generated by Gemini AI.
It reads summary files from the Summaries_FR_TXT directory and updates the corresponding
Omeka S items by adding or updating the dcterms:abstract field.

The script:
1. Reads all .txt files from the Summaries_FR_TXT directory
2. For each summary file, extracts the item ID from the filename
3. Fetches the current item data from Omeka S to preserve existing fields
4. Updates or adds the dcterms:abstract field with the generated summary
5. Sends the updated data back to Omeka S via PATCH request

Requirements:
- Environment variables: OMEKA_BASE_URL, OMEKA_KEY_IDENTITY, OMEKA_KEY_CREDENTIAL
- Summary files in Summaries_FR_TXT directory (generated by 02_gemini_generate_summaries.py)
- Omeka S API access with appropriate permissions
"""

import os
import sys
from tqdm import tqdm
import logging

# Configure logging to track script execution and errors
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Shared Omeka client
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from common.omeka_client import OmekaClient

# Omeka S property configuration
DCTERMS_ABSTRACT_PROPERTY_ID = 1  # Property ID for dcterms:abstract in Omeka S


def update_item_summary(client: OmekaClient, item_id, new_summary):
    """
    Update an Omeka S item with a new French summary in the dcterms:abstract field.

    Args:
        client: OmekaClient instance
        item_id (str): The unique identifier of the Omeka S item to update
        new_summary (str): The French summary text to add to the item

    Returns:
        bool: True if update was successful, False otherwise
    """
    item_data = client.get_item(int(item_id))
    if not item_data:
        logging.warning(f"No data found for item {item_id}. Skipping update.")
        return False

    if 'dcterms:abstract' not in item_data:
        item_data['dcterms:abstract'] = []

    summary_found = False
    for desc in item_data['dcterms:abstract']:
        if desc.get('property_id') == DCTERMS_ABSTRACT_PROPERTY_ID:
            desc['@value'] = new_summary
            desc['type'] = 'literal'
            desc['property_label'] = 'Abstract'
            summary_found = True
            logging.info(f"Updated existing abstract for item {item_id}")
            break

    if not summary_found:
        item_data['dcterms:abstract'].append({
            "type": "literal",
            "property_id": DCTERMS_ABSTRACT_PROPERTY_ID,
            "property_label": "Abstract",
            "is_public": True,
            "@value": new_summary
        })
        logging.info(f"Added new abstract for item {item_id}")

    return client.update_item(int(item_id), item_data)


def main():
    """
    Main execution function for updating Omeka S items with French summaries.
    
    This function orchestrates the entire update process:
    1. Validates environment variables
    2. Locates the summary files directory
    3. Processes each summary file to update corresponding Omeka S items
    4. Provides progress tracking and error reporting
    
    The function expects summary files to be named with the pattern: {item_id}.txt
    where item_id corresponds to the Omeka S item identifier.
    
    Environment Variables Required:
        - OMEKA_BASE_URL: Base URL for the Omeka S API
        - OMEKA_KEY_IDENTITY: API key identity for authentication
        - OMEKA_KEY_CREDENTIAL: API key credential for authentication
    
    Returns:
        None: Exits with status code 0 on success, 1 on error
    """
    # Initialize shared Omeka client
    try:
        client = OmekaClient.from_env()
    except ValueError as e:
        logging.error(str(e))
        return 1

    # Locate the summary files directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    summary_folder = os.path.join(script_dir, "Summaries_FR_TXT")

    if not os.path.exists(summary_folder):
        logging.error(f"Summary folder not found: {summary_folder}")
        logging.error("Please run 02_gemini_generate_summaries.py first to generate summary files.")
        return 1

    # Get all .txt files in the summary folder
    txt_files = [f for f in os.listdir(summary_folder) if f.endswith('.txt')]

    if not txt_files:
        logging.warning(f"No .txt files found in {summary_folder}")
        return 0

    logging.info(f"Found {len(txt_files)} summary files to process")

    # Process each summary file
    success_count = 0
    error_count = 0
    
    for txt_file in tqdm(txt_files, desc="Updating Omeka S items with summaries"):
        # Extract item ID from filename (remove .txt extension)
        item_id = os.path.splitext(txt_file)[0]
        txt_path = os.path.join(summary_folder, txt_file)

        try:
            # Read the summary content
            with open(txt_path, 'r', encoding='utf-8') as f:
                summary_text = f.read().strip()
            
            # Only proceed if summary_text is not empty
            if summary_text:
                if update_item_summary(client, item_id, summary_text):
                    success_count += 1
                else:
                    error_count += 1
            else:
                logging.warning(f"Skipping item {item_id}: Summary file is empty")
                
        except FileNotFoundError:
            logging.error(f"Summary file not found: {txt_path}")
            error_count += 1
        except Exception as e:
            logging.error(f"Error processing file {txt_path}: {e}")
            error_count += 1

    # Final summary of operations
    logging.info(f"Update process completed:")
    logging.info(f"  - Successfully updated: {success_count} items")
    logging.info(f"  - Errors encountered: {error_count} items")
    logging.info(f"  - Total processed: {len(txt_files)} files")
    
    return 0 if error_count == 0 else 1


if __name__ == "__main__":
    exit_code = main()
    exit(exit_code)
